apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-api
spec:
  replicas: 1
  selector:
    matchLabels:
      component: tasks-api
  template:
    metadata:
      labels:
        component: tasks-api
    spec:
      containers:
        - name: tasks-api
          image: dennitorf/task-api:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
